# ignorezero / ignorealpha -> esquinas redondeadas

# animation / noanim <- quickshell

# xray <- quickshell

# blurpopups <- quickshell menus/tooltips

layerrule {
  name = disable-animation-screenshot
  no_anim = on
  match:namespace = selection
}
