# Ignore maximize requests from apps.
windowrule {
  name = maximize-requests
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = dragging-xwayland
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# Idle inhibit
# [ games / yt / media players / image viewers ...]
windowrule {
  name = idle-inhibit-class
  match:class = ^(mpv)$
  idle_inhibit = always
}

# Picture in Picture
windowrule {
  name = picture-in-picture
  match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
  float = on
  keep_aspect_ratio = on
  move = (monitor_w*.73) (monitor_h*.72) 
  size = (monitor_w*.25) (monitor_h*.25)
  pin = on
}

# Floating
windowrule {
  name = floating-titles
  match:title = ^(Library)(.*)$|^(Save As)(.*)$|^(File Upload)(.*)$
  float = on
  center = on
  animation = slide
}

windowrule {
  name = floating-classes
  match:class = ^(blueman-manager)$|^(mpv)$|^(nwg-look)$
  float = on
  center = on
  animation = slide
}

# Transparency (opacity = 0.8)
# [...]

# Tearing (Games -> immediate = on)
#windowrule = match:title .*\.exe, immediate on
#windowrule = match:title .*minecraft.*, immediate on
#windowrule = match:class ^(steam_app).*, immediate on

# Jetbrains
#windowrule = match:class ^jetbrains-.*$, match:float 1, match:title ^$|^\s$|^win\d+$, no_initial_focus on

# XWayland
#windowrule = no_dim true, match:xwayland 1, match:title win[0-9]+
#windowrule = no_shadow true, match:xwayland 1, match:title win[0-9]+
#windowrule = rounding 10, match:xwayland 1, match:title win[0-9]+
