#!/usr/bin/env bash

theme="$1"
libdir="$HOME/.local/scripts/theme-switch-lib"
colors="$XDG_CACHE_HOME/colors/$theme.txt"

if [ ! -f "$colors" ]; then
	notify-send "Theme switcher" "Color theme '$theme' not found!"
	exit 1
fi

"$libdir/foot-theme.sh" "$theme"
"$libdir/wofi-theme.sh" "$theme"
"$libdir/river-theme.sh" "$theme"
"$libdir/dunst-theme.sh" "$theme"
"$libdir/waybar-theme.sh" "$theme"

echo "$1" > "$XDG_CACHE_HOME/colors/.current"
