#!/bin/bash

#---------#
# Entorno #
#---------#

export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_DESKTOP=river
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1

systemctl --user import-environment \
  WAYLAND_DISPLAY \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_TYPE \
  XDG_SESSION_DESKTOP \
  QT_QPA_PLATFORM \
  MOZ_ENABLE_WAYLAND

dbus-update-activation-environment --systemd \
  WAYLAND_DISPLAY \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_TYPE \
  XDG_SESSION_DESKTOP \
  QT_QPA_PLATFORM \
  MOZ_ENABLE_WAYLAND

#-----------#
# Variables #
#-----------#

# Aplicaciones
term="foot"
menu="wofi --show drun"
files="thunar"

# Rivertile
gaps=8
padding=8
layout="rivertile"

# Input y teclas
mod="Mod4"
keyboard="latam"
xplode="*BY_Tech_Usb_Gaming_Keyboard*" # Teclado Xplode

# Apariencia
bg="0x24273a"
focus="0xc6a0f6"
unfocus="0xb7bdf8"
urgent="0xed8796"
width=4
cursor="Adwaita"

#-----------#
# Rivertile #
#-----------#

riverctl default-layout $layout
rivertile -main-location left -main-count 1 -main-ratio 0.5 -view-padding $gaps -outer-padding $padding &

#---------------#
# Configuration #
#---------------#

riverctl default-attach-mode bottom

riverctl background-color $bg
riverctl border-color-focused $focus
riverctl border-color-unfocused $unfocus
riverctl border-color-urgent $urgent

riverctl border-width $width

riverctl hide-cursor timeout 0
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp disabled
riverctl set-repeat 60 250
riverctl xcursor-theme $cursor

#----------------------#
# Output Configuration #
#----------------------#
output="eDP-1"
scale="2"
riverctl spawn "wlr-randr --output $output --scale $scale"

#---------------------#
# Input Configuration #
#---------------------#

riverctl keyboard-layout $keyboard

riverctl input "pointer*" accel-profile flat
riverctl input "pointer*" pointer-accel 0.3

riverctl input "*Touchpad" natural-scroll enabled
riverctl input "*Touchpad" scroll-factor 1.0
riverctl input "*Touchpad" tap enabled
riverctl input "*Touchpad" tap-button-map left-right-middle
riverctl input "*Touchpad" scroll-method two-finger

#----------#
# Mappings #
#----------#

# General
riverctl map normal $mod Q spawn "$term"
riverctl map normal $mod R spawn "$menu"
riverctl map normal $mod E spawn "$files"
riverctl map normal $mod C close
riverctl map normal $mod M exit

# Ventanas
riverctl map normal $mod F toggle-float
riverctl map normal $mod P toggle-fullscreen

riverctl map normal $mod H focus-view left
riverctl map normal $mod J focus-view down
riverctl map normal $mod K focus-view up
riverctl map normal $mod L focus-view right

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

riverctl map normal $mod Left  snap left
riverctl map normal $mod Down  snap down
riverctl map normal $mod Up    snap up
riverctl map normal $mod Right snap right

# Stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod Tab zoom

#------#
# Tags #
#------#

# Workspaces 1 a 8
for i in $(seq 1 8); do
    tag=$((1 << ($i - 1)))

    # Ir a un tag (analogia a workspace)
    riverctl map normal $mod $i set-focused-tags $tag

    # Mover ventana al tag Y cambiar a ese tag
    riverctl map normal $mod+Shift $i spawn "riverctl set-view-tags $tag && riverctl set-focused-tags $tag"

    # Cambiar tags mostrados al mismo tiempo
    # riverctl map normal $mod+Control $i toggle-focused-tags $tag

    # Cambiar el tag de la ventana
    # riverctl map normal $mod+Shift+Control $i toggle-view-tags $tag
done

# Workspace secreto
tag9=256

riverctl map normal $mod+Shift S set-view-tags $tag9
riverctl map normal $mod S set-focused-tags $tag9

#------------#
# Multimedia #
#------------#

for mode in normal locked; do
    riverctl map -repeat $mode None XF86AudioRaiseVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1 && notif-volumen.sh'
    riverctl map -repeat $mode None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notif-volumen.sh'
    riverctl map $mode None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notif-volumen.sh'

    riverctl map $mode None XF86AudioMicMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'

    riverctl map -repeat $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5% && notif-brightness.sh'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%- && notif-brightness.sh'
done

#--------------#
# App Shorcuts #
#--------------#

riverctl map normal $mod V spawn "cliphist list | wofi -S dmenu | cliphist decode | wl-copy"

riverctl map normal Shift+Alt S spawn "screenshot.sh area"
riverctl map normal Control+Alt S spawn "screenshot.sh save"


# Lock mode para despues ---

#-------#
# Rules #
#-------#

# . . .

#-----------#
# Autostart #
#-----------#

riverctl spawn dunst

riverctl spawn "wl-paste --watch cliphist store"
