#!/bin/bash

# check si se pasa argumento
if [ -z "$1" ]; then
    echo "  Aclarar path dentro de ~/Pictures/wallpapers/.\nEjemplo: wg"
    exit 1
fi

# armar el path 
WALLPAPER_DIR="$HOME/Pictures/wallpapers/$1"

# validar que exista
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "  No existe carpeta en '$WALLPAPER_DIR'"
    exit 1
fi

# wallpaper aleatorio
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | shuf -n 1)

# validar que haya al menos un archivo
if [ -z "$WALLPAPER" ]; then
    echo "  No hay imagenes dentro de '$WALLPAPER_DIR'"
    exit 1
fi

# poner el wallpaper
# el flag -p lo saco de "xfconf-query -c xfce4-desktop -m"
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP-1/workspace0/last-image -s "$WALLPAPER"

# generar esquema con flag -n para no cambiar el fondo
wal -i "$WALLPAPER" -n -e -t

echo "  Utilizando $WALLPAPER_DIR"
