#!/usr/bin/env bash

msgTag="brightness-indicator"
percent=$(brightnessctl g --machine-readable | cut -d, -f4 | tr -d '%')

dunstify -a "Brightness" -u low -i display-brightness-symbolic \
  -h string:x-dunst-stack-tag:$msgTag \
  -h int:value:"$percent" "Brightness: ${percent}%"
