#!/bin/bash

options="Shut Down\nReboot\nLock\nSuspend\nHibernate"

chosen=$(echo -e "$options" | wofi -d --height=180  --cache-file /dev/null)

case "$chosen" in
    "Shut Down") systemctl poweroff ;;
    "Reboot") systemctl reboot ;;
    "Lock") loginctl lock-session ;;
    "Suspend") systemctl suspend ;;
    "Hibernate") systemctl hibernate ;;
    *) exit 0 ;;
esac
