[main]
term=foot
locked-title=no

font=CaskaydiaMono Nerd Font:size=12

dpi-aware=no
pad=0x0

bold-text-in-bright=no
selection-target=clipboard

[security]
osc52=enabled

[bell]
system=no
urgent=no
notify=no
visual=no

[scrollback]
lines=1000
multiplier=5.0
indicator-position=none
#indicator-format=percentage

[url]
launch=xdg-open ${url}

[cursor]
style=block
blink=no
unfocused-style=none
blink-rate=500

[colors-dark]
alpha=1.0
alpha-mode=default

background=0a0a0a
foreground=ffffff

cursor=000000 ffffff

regular0=16181a
regular1=ff6e5e
regular2=5eff6c
regular3=f1ff5e
regular4=5ea1ff
regular5=bd5eff
regular6=5ef1ff
regular7=ffffff
bright0=3c4048
bright1=ff6e5e
bright2=5eff6c
bright3=f1ff5e
bright4=5ea1ff
bright5=bd5eff
bright6=5ef1ff
bright7=ffffff

[csd]
preferred=server

[key-bindings]
scrollback-up-page=none
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=none
search-start=none
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=none
minimize=none
maximize=none
fullscreen=Alt+Return
pipe-visible=none
pipe-scrollback=none
pipe-selected=none
pipe-command-output=none
show-urls-launch=none
show-urls-copy=none
show-urls-persistent=none
prompt-prev=none
prompt-next=none
unicode-input=Control+Shift+u
#color-theme-switch-1=none
#color-theme-switch-2=none
#color-theme-toggle=none
noop=none
quit=none

[search-bindings]
cancel=none
commit=none
find-prev=none
find-next=none
cursor-left=none
cursor-left-word=none
cursor-right=none
cursor-right-word=none
cursor-home=none
cursor-end=none
delete-prev=none
delete-prev-word=none
delete-next=none
delete-next-word=none
delete-to-start=none
delete-to-end=none
extend-char=none
extend-to-word-boundary=none
extend-to-next-whitespace=none
extend-line-down=none
extend-backward-char=none
extend-backward-to-word-boundary=none
extend-backward-to-next-whitespace=none
extend-line-up=none
clipboard-paste=none
primary-paste=none
unicode-input=none
scrollback-up-page=none
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none

[url-bindings]
cancel=none
toggle-url-visible=none

[text-bindings]
\x03=none

[mouse-bindings]
scrollback-up-mouse=BTN_WHEEL_BACK
scrollback-down-mouse=BTN_WHEEL_FORWARD
font-increase=Control+BTN_WHEEL_BACK
font-decrease=Control+BTN_WHEEL_FORWARD
selection-override-modifiers=Shift
primary-paste=BTN_MIDDLE
select-begin=BTN_LEFT
select-begin-block=Control+BTN_LEFT
select-extend=BTN_RIGHT
select-extend-character-wise=Control+BTN_RIGHT
select-word=BTN_LEFT-2
select-word-whitespace=Control+BTN_LEFT-2
select-quote = BTN_LEFT-3
select-row=BTN_LEFT-4
